trigger: none

#TODO variabile hardcodate, trebuie folositi parametrii
variables:
  - name: repository
    value: 'proiectING'
  - name: dockerfile
    value: '$(Build.SourcesDirectory)/proiectING/Dockerfile'
  - name: containerRegistry
    value: 'testAcrMara'  

stages:
  - stage: Build
    displayName: Build and push image
    dependsOn:
    jobs:
    - job: Build
      displayName: Build job
      steps:
      - task: Docker@2
        displayName: Build and push image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ variables.repository }}
          dockerfile: ${{ variables.dockerfile }}
          containerRegistry: ${{ variables.containerRegistry }}
          tags: $(Build.BuildId)
  - stage: Deploy
    displayName: Deploy app
    dependsOn: Build
    jobs:
    - job: Deploy
      displayName: Deploy app
      steps:
      #TODO implement login part
      - task: Docker@2
        displayName: Login to ACR
        inputs: 
          command: login
          containerRegistry: ${{ variables.containerRegistry }}
      - script: docker run testacrmara.azurecr.io/proiecting:183
      