---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flaskproiect
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: flaskproiect
  template:
    metadata: 
      labels:
        app: flaskproiect
    spec:
      containers:
      - name: flaskproiect
        image: maraxd/flask-app:latest
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flaskproiect
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer